---
- hosts: control
  become: true
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install MySQL server
      apt:
        name: mysql-server
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Create MySQL database
      mysql_db:
        name: aws_instructor
        state: present

    - name: Create MySQL user
      mysql_user:
        name: instructor
        password: password
        priv: 'aws_instructor.*:ALL'
        state: present

    - name: Copy SQL file to remote server
      copy:
        src: /home/ubuntu/Ansible-Intro/aws_provisioning.sql
        dest: /tmp/aws_provisioning.sql

    - name: Execute SQL file to create tables
      command: mysql -u instructor -ppassword aws_instructor < /tmp/aws_provisioning.sql
